server:
  port: 9751
  # servlet:
  #   context-path: /monitor

spring:
  application:
    name: elastic-monitor
  datasource:
    url: jdbc:mysql://192.168.30.78:43306/elastic_monitor
    username: dbapp
    password: jY%kng8cc&
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
  windows:
    use:
      mock: false
  aop:
    proxy-target-class: true

# MyBatis ??
mybatis:
  mapper-locations: classpath:myibatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# ????
logging:
  path: D:/lcc/logs
  config: classpath:logback-windows.xml

# ??????
plugins:
  config:
    dir: E:\Ideaproject\elastic\dipper-elastic-monitor\elastic-service-provider\src\main\resources\plugins
  jar:
    dir: plugins

prefabricate:
  template:
    path: \\elastic-handler-provider\\src\\main\\resources\\template\\prefabricate